spring:
  application:
    name: databasePractice
  datasource:
    url: jdbc:mysql://localhost:3306/practice_springjpa
    username: root
    password: Skuk13579@

  jpa:
    hibernate:
#      ddl-auto: update
       ddl-auto: validate #shifting to flyway migration now change in schema will not directly affect the table
    show-sql: true

  flyway:
    enable: true
    location: classpath:db/migration

